CREATE TABLE books (
  ID SERIAL PRIMARY KEY,
  title VARCHAR(255) NOT NULL
  author VARCHAR(255) NOT NULL,
  cover VARCHAR(255) NOT NULL,
  date BIGINT NOT NULL
);

CREATE TABLE users (
  ID SERIAL PRIMARY KEY,
  login VARCHAR(255) NOT NULL
  password VARCHAR(255) NOT NULL,
  mail VARCHAR(255) NOT NULL,
);
